services:
  - type: web
    name: just-we-backend
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      gunicorn --chdir backend app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.18
      - key: FLASK_ENV
        value: development
      - key: GROQ_API_KEY
        sync: false 