services:
  - type: web
    name: calmspace-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python backend/app.py"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 5000
    autoDeploy: true
    healthCheckPath: /api/health 